def conquistas():

    arquivo = open('imagens/nomes.txt', 'r')

    premio1 = arquivo.readline()
    premio2 = arquivo.readline()
    premio3 = arquivo.readline()
    premio4 = arquivo.readline()
    premio5 = arquivo.readline()
    premio6 = arquivo.readline()
    premio7 = arquivo.readline()
    premio8 = arquivo.readline()
    premio9 = arquivo.readline()
    premio10 = arquivo.readline()
    premio11 = arquivo.readline()
    premio12 = arquivo.readline()
    premio13 = arquivo.readline()
    premio14 = arquivo.readline()
    premio15 = arquivo.readline()
    premio16 = arquivo.readline()
    premio17 = arquivo.readline()
    premio18 = arquivo.readline()
    premio19 = arquivo.readline()
    premio20 = arquivo.readline()
    premio21 = arquivo.readline()
    premio22 = arquivo.readline()
    premio23 = arquivo.readline()
    premio24 = arquivo.readline()
    premio25 = arquivo.readline()
    premio26 = arquivo.readline()
    premio27 = arquivo.readline()
    premio28 = arquivo.readline()
    premio29 = arquivo.readline()
    premio30 = arquivo.readline()

    arquivo.close()

    return

conquistas()